### PR TITLE
Replacement of sleep commands with oc wait

### PR DESCRIPTION
**Pull request by carlmes**
Updated the bootstrap script to use `oc wait` instead of relying on `sleep 45` for various components to change to ready state.

oc wait docs: https://docs.openshift.com/container-platform/4.11/cli_reference/openshift_cli/developer-cli-commands.html#oc-wait

kubectl wait docs: https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#wait

### CODE REVIEW

**Comment by carlmes** [comment]
All the changes made to `kustomize.yaml` files are to fix this deprecation warning messages:

`# Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesJson6902' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.

Fixed fields:
  patchesJson6902 -> patches
  patchesStrategicMerge -> patches
  commonLabels -> labels
  vars -> replacements`

**Comment by carlmes** [comment]
Results of executing the bootstrap script on a brand new cluster hosted on RHDS:

```
▶ ./bootstrap.sh
Validating CLI tool: oc
/usr/local/bin/oc
auto-complete: . <(oc completion bash)
Client Version: 4.10.0-202207291908.p0.ge29d58e.assembly.stream-e29d58e
Server Version: 4.11.8
Kubernetes Version: v1.24.0+dc5a2fd

Validating CLI tool: kustomize
/usr/local/bin/kustomize
auto-complete: . <(kustomize completion bash)
v5.0.0

Validating CLI tool: kubeseal
/Users/carl/Development/rh-intelligent-application-practice/openshift-cluster-bootstrap-gitops/tmp/bin/kubeseal

kubeseal version: 0.19.4

Kubernetes control plane is running at https://api.cluster-sdwj9.sdwj9.sandbox1543.opentlc.com:6443
opentlc-mgr

Using Existing Sealed Secret: bootstrap/base/sealed-secrets-secret.yaml

Installing GitOps Operator.
subscription.operators.coreos.com/openshift-gitops-operator created
Waiting for deployment of the gitops-operator-controller-manager to begin...
Error from server (NotFound): deployments.apps "gitops-operator-controller-manager" not found
Error from server (NotFound): deployments.apps "gitops-operator-controller-manager" not found
NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
gitops-operator-controller-manager   0/1     1            0           5s
Waiting for gitops-operator-controller-manager to start...
deployment.apps/gitops-operator-controller-manager condition met
Waiting for openshift-gitops namespace to be created...
namespace/openshift-gitops condition met
Waiting for deployments to start...
deployment.apps/cluster condition met
Checking status of all openshift-gitops pods
Waiting for deployment/cluster state to be condition=Available...
deployment.apps/cluster condition met
Waiting for deployment/kam state to be condition=Available...
deployment.apps/kam condition met
Waiting for statefulset/openshift-gitops-application-controller state to be jsonpath={.status.readyReplicas}=1...
pod/openshift-gitops-application-controller-0 condition met
Waiting for deployment/openshift-gitops-applicationset-controller state to be condition=Available...
deployment.apps/openshift-gitops-applicationset-controller condition met
Waiting for deployment/openshift-gitops-redis state to be condition=Available...
deployment.apps/openshift-gitops-redis condition met
Waiting for deployment/openshift-gitops-repo-server state to be condition=Available...
deployment.apps/openshift-gitops-repo-server condition met
Waiting for deployment/openshift-gitops-server state to be condition=Available...
deployment.apps/openshift-gitops-server condition met

OpenShift GitOps successfully installed.
1) bootstrap/overlays/rhdp-4.10/  3) bootstrap/overlays/rhdp-4.9/
2) bootstrap/overlays/rhdp-4.11/  4) bootstrap/overlays/rosa/
Please enter a number to select a bootstrap folder: 2
Selected: bootstrap/overlays/rhdp-4.11/
Apply overlay to override default instance
namespace/sealed-secrets created
customresourcedefinition.apiextensions.k8s.io/sealedsecrets.bitnami.com created
serviceaccount/sealed-secrets-controller created
role.rbac.authorization.k8s.io/sealed-secrets-key-admin created
role.rbac.authorization.k8s.io/sealed-secrets-service-proxier created
clusterrole.rbac.authorization.k8s.io/secrets-unsealer created
rolebinding.rbac.authorization.k8s.io/sealed-secrets-controller created
rolebinding.rbac.authorization.k8s.io/sealed-secrets-service-proxier created
clusterrolebinding.rbac.authorization.k8s.io/argocd-application-controller-cluster-admin created
clusterrolebinding.rbac.authorization.k8s.io/sealed-secrets-controller created
secret/sealed-secrets-keyh87g5 created
service/sealed-secrets-controller created
Warning: would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "sealed-secrets-controller" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "sealed-secrets-controller" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "sealed-secrets-controller" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "sealed-secrets-controller" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
deployment.apps/sealed-secrets-controller created
appproject.argoproj.io/cluster-config created
application.argoproj.io/cluster-config-app-of-apps created
applicationset.argoproj.io/cluster-operators-applicationset created
Warning: resource argocds/openshift-gitops is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by oc apply. oc apply should only be used on resources created declaratively by either oc create --save-config or oc apply. The missing annotation will be patched automatically.
argocd.argoproj.io/openshift-gitops configured
group.user.openshift.io/gitopsadmins created
Checking status of all openshift-gitops pods
Waiting for deployment/cluster state to be condition=Available...
deployment.apps/cluster condition met
Waiting for deployment/kam state to be condition=Available...
deployment.apps/kam condition met
Waiting for statefulset/openshift-gitops-application-controller state to be jsonpath={.status.readyReplicas}=1...
pod/openshift-gitops-application-controller-0 condition met
Waiting for deployment/openshift-gitops-applicationset-controller state to be condition=Available...
deployment.apps/openshift-gitops-applicationset-controller condition met
Waiting for deployment/openshift-gitops-redis state to be condition=Available...
deployment.apps/openshift-gitops-redis condition met
Waiting for deployment/openshift-gitops-repo-server state to be condition=Available...
deployment.apps/openshift-gitops-repo-server condition met
Waiting for deployment/openshift-gitops-server state to be condition=Available...
deployment.apps/openshift-gitops-server condition met
Restart the application-controller to start the sync
pod "openshift-gitops-application-controller-0" deleted

GitOps has successfully deployed!  Check the status of the sync here:
https://openshift-gitops-server-openshift-gitops.apps.cluster-sdwj9.sdwj9.sandbox1543.opentlc.com
```

**Comment by strangiato** [comment]
Just tested it out and everything looks good.  I made a few minor updates to the scripts and kustomization files.   Feel free to review those and merge when you are ready.

**Comment by carlmes** [comment]
Looks great! All checks pass, so merge inbound 👍

**Pull request merged**
